name: Auto-update Investment Chart

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install gspread pandas plotly oauth2client numpy

    - name: Setup Google Service Account
      env:
        GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
      run: echo "Service Account listo"

    - name: Generate chart
      env:
        GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
      run: python generate_chart.py

    - name: Commit & Push HTML
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add investment_chart.html
        git commit -m "Auto-update chart" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/acasan7/charts.git main
